---
title: "Coca-Cola Overview"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Group Budget

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(readxl)
library(dplyr)
library(knitr)
library(kableExtra)

budget <- read_excel("timeline.xlsx", sheet = "Sheet2", 
    col_types = c("date", "text", "text", 
        "numeric", "text", "numeric", "numeric"))
budget$DATE <- as.Date(budget$DATE) %>% format("%b/%d")


table <- budget[,c(1,3:7)] 
table$Total <- paste('€',formatC(table$Total, big.mark=',', format = NULL ))
table$withVAT <- paste('€',formatC(table$withVAT, big.mark=',', format = NULL ))
table <- sapply(table,as.character)
table[is.na(table)] <- " "


table %>%  
  kable() %>% kable_styling(bootstrap_options = c("striped","condensed","responsive"),font_size = 10, fixed_thead = list(enabled=T, background="#EF8319")) %>% column_spec(6, 
bold = T, width = "2cm") %>% 
  row_spec(nrow(table), bold = T, color = "black", background ="#EF8319")


```

Column {data-width=500}
-----------------------------------------------------------------------


### Map

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(readxl)
library(rbokeh)

timeline <- read_excel("timeline.xlsx", sheet = "Sheet3")
timeline$Category <- as.factor(timeline$Category)
timeline$Longitude <- as.numeric(timeline$Longitude)
timeline$Latitude <- as.numeric(timeline$Latitude)


style <- '[{"featureType": "all","elementType": "all","stylers": [{"saturation": "32"},{"lightness": "-3"},{"visibility": "on"},{"weight": "1.18"}]},{"featureType": "administrative","elementType": "labels","stylers": [{"visibility": "off"}]},{"featureType": "landscape","elementType": "labels","stylers": [{"visibility": "off"}]},{"featureType": "landscape.man_made","elementType": "all","stylers": [{"saturation": "-70"},{"lightness": "14"}]},{"featureType": "poi","elementType": "labels","stylers": [
{"visibility": "off"}]},{"featureType": "road","elementType": "labels","stylers": [
{"visibility": "off"}]},{"featureType": "transit","elementType": "labels",
"stylers": [{"visibility": "off"}]},{"featureType": "water","elementType": "all",
"stylers": [{"saturation": "100"},{"lightness": "-14"}]},{"featureType": "water",
"elementType": "labels","stylers": [{"visibility": "off"},{"lightness": "12"}]}]'

key <- "AIzaSyDaT2Nf0wgJDoAuKQV3PR07f5BEHi4qxjU"

time_map <- gmap(api_key = key,
  title = "Hotels and venues mentioned in the Quotation",
lat = 41.3858148, lng = 2.1692236, zoom = 14, map_style = style)

time_map %>% 
  ly_points(x= Longitude, y = Latitude, data = timeline, size = 10,
    alpha = 7,fill_color = Category, line_alpha = 0, 
    hover = c(Location, Address))
```



